# Generated by Django 5.1 on 2024-09-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
